function setUpHTMLFixture() {
setFixtures(
     '<table><tbody class="text-canter">'
       +'<tr>'
         +'<td class="text-center" id="frame-1-roll-1">0</td>'
         +'<td class="text-center" id="frame-1-roll-2">0</td>'
         +'<td class="text-center" id="frame-2-roll-1">0</td>'
         +'<td class="text-center" id="frame-2-roll-2">0</td>'
         +'<td class="text-center" id="frame-3-roll-1">0</td>'
         +'<td class="text-center" id="frame-3-roll-2">0</td>'
         +'<td class="text-center" id="frame-4-roll-1">0</td>'
         +'<td class="text-center" id="frame-4-roll-2">0</td>'
         +'<td class="text-center" id="frame-5-roll-1">0</td>'
         +'<td class="text-center" id="frame-5-roll-2">0</td>'
         +'<td class="text-center" id="frame-6-roll-1">0</td>'
         +'<td class="text-center" id="frame-6-roll-2">0</td>'
         +'<td class="text-center" id="frame-7-roll-1">0</td>'
         +'<td class="text-center" id="frame-7-roll-2">0</td>'
         +'<td class="text-center" id="frame-8-roll-1">0</td>'
         +'<td class="text-center" id="frame-8-roll-2">0</td>'
         +'<td class="text-center" id="frame-9-roll-1">0</td>'
         +'<td class="text-center" id="frame-9-roll-2">0</td>'
         +'<td class="text-center" id="frame-10-roll-1">0</td>'
         +'<td class="text-center" id="frame-10-roll-2">0</td>'
         +'<td class="text-center" id="frame-10-roll-3">0</td>'
        +'</tr>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-0">0</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-1">1</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-2">2</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-3">3</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-4">4</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-5">5</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-6">6</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-7">7</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-8">8</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-9">9</button>'
        +'<button type="button" class="btn btn-primary btn-lg" id="num-10">10</button>'
        +'<tr>'
          +'<td colspan="2" class="text-center" id="frame-1">0</td>'
          +'<td colspan="2" class="text-center" id="frame-2">0</td>'
          +'<td colspan="2" class="text-center" id="frame-3">0</td>'
          +'<td colspan="2" class="text-center" id="frame-4">0</td>'
          +'<td colspan="2" class="text-center" id="frame-5">0</td>'
          +'<td colspan="2" class="text-center" id="frame-6">0</td>'
          +'<td colspan="2" class="text-center" id="frame-7">0</td>'
          +'<td colspan="2" class="text-center" id="frame-8">0</td>'
          +'<td colspan="2" class="text-center" id="frame-9">0</td>'
          +'<td colspan="2" class="text-center" id="frame-10">0</td>'
        +'</tr>'
        +'<tr>'
          +'<td colspan="20" class="text-center total-score">Total Score : <span id="total-score"></span></td>'
        +'</tr></tbody></table>'
            );
 }

module.exports = setUpHTMLFixture();
