env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jasmine: true
  jquery: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Roll: writable
  Frame: writable
  Scorecard: writable
parserOptions:
  ecmaVersion: 2018
rules: {
    'no-plusplus': [2, { allowForLoopAfterthoughts: true }]
}
