env:
  browser: true
  es6: true
  jasmine: true
plugins:
  - jasmine
extends:
  - 'plugin:jasmine/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
