describe('Spare Game', function() {
  it('should show score of 105 after mixed rolls with some spares (none in final frame)', function() {
    var scorecard = new Scorecard;
    scorecard.startGame();
    scorecard.roll(5);
    scorecard.roll(5);
    scorecard.roll(9);
    scorecard.roll(1);
    scorecard.roll(3);
    scorecard.roll(6);
    scorecard.roll(8);
    scorecard.roll(2);
    scorecard.roll(9);
    scorecard.roll(0);
    scorecard.roll(5);
    scorecard.roll(2);
    scorecard.roll(4);
    scorecard.roll(5);
    scorecard.roll(2);
    scorecard.roll(8);
    scorecard.roll(1);
    scorecard.roll(4);
    scorecard.roll(2);
    scorecard.roll(2);
    expect(scorecard.totalScore).toEqual(105);
  });
  it('should show score of 114 after mixed rolls with some spares (final frame is spare)', function() {
    var scorecard = new Scorecard;
    scorecard.startGame();
    scorecard.roll(5);
    scorecard.roll(5);
    scorecard.roll(9);
    scorecard.roll(1);
    scorecard.roll(3);
    scorecard.roll(6);
    scorecard.roll(8);
    scorecard.roll(2);
    scorecard.roll(9);
    scorecard.roll(0);
    scorecard.roll(5);
    scorecard.roll(2);
    scorecard.roll(4);
    scorecard.roll(5);
    scorecard.roll(2);
    scorecard.roll(8);
    scorecard.roll(1);
    scorecard.roll(4);
    scorecard.roll(2);
    scorecard.roll(8);
    scorecard.roll(3);
    expect(scorecard.totalScore).toEqual(114);
  });
});
