describe('Strike Game', function() {
  it('should show score of 152 after mixed rolls with some spares and strikes (none in final frame)', function() {
    var scorecard = new Scorecard;
    scorecard.startGame();
    scorecard.roll(5);
    scorecard.roll(3);
    scorecard.roll(10);
    scorecard.roll(6);
    scorecard.roll(4);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(3);
    scorecard.roll(4);
    scorecard.roll(2);
    scorecard.roll(7);
    scorecard.roll(4);
    scorecard.roll(5);
    scorecard.roll(3);
    scorecard.roll(6);
    expect(scorecard.totalScore).toEqual(152);
  });
  it('should show score of 162 after mixed rolls with some spares and strike in final frame', function() {
    var scorecard = new Scorecard;
    scorecard.startGame();
    scorecard.roll(5);
    scorecard.roll(3);
    scorecard.roll(10);
    scorecard.roll(6);
    scorecard.roll(4);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(3);
    scorecard.roll(4);
    scorecard.roll(2);
    scorecard.roll(7);
    scorecard.roll(4);
    scorecard.roll(5);
    scorecard.roll(10);
    scorecard.roll(6);
    scorecard.roll(3);
    expect(scorecard.totalScore).toEqual(162);
  });
  it('should show score of 173 after mixed rolls with some spares and 3 strikes in final frame', function() {
    var scorecard = new Scorecard;
    scorecard.startGame();
    scorecard.roll(5);
    scorecard.roll(3);
    scorecard.roll(10);
    scorecard.roll(6);
    scorecard.roll(4);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(3);
    scorecard.roll(4);
    scorecard.roll(2);
    scorecard.roll(7);
    scorecard.roll(4);
    scorecard.roll(5);
    scorecard.roll(10);
    scorecard.roll(10);
    scorecard.roll(10);
    expect(scorecard.totalScore).toEqual(173);
  });
});
